exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

title : L.A. Spring
tagline: L.A. Spring are a 3-piece indie pop band, based in London.
description: L.A. Spring are a 3-piece indie pop band, based in London. 'Heart and Soul' out 27/1/17.
author :
  name : L.A. Spring
  email : wearelaspring@gmail.com
  twitter : wearelaspring

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://wearelaspring.com

gems:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-minifier
  - jekyll-assets
  - autoprefixer-rails
